version: '3.7'

services:
  app:
    build: docker/development
    command: sh -c "cd app && php artisan serve --host=0.0.0.0 --port=8080"
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: lavanderia
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
